#!/bin/bash

set -e

PATH=~/tools/JLink_Linux_V640b_x86_64:$PATH
BOOTLOADER=../bootloaders/build/m0/zero/fk-bootloaders-samd21large.bin
TEST=build/firmware/test/fk-naturalist-test.bin
MAIN=build/firmware/main/fk-naturalist-standard.bin

pushd build
cmake ../
make -j2
popd

echo Writing bootloader firmware...

JLinkExe -if SWD -device ATSAMD21G18 -speed 4000 -autoconnect 1 <<EOF
exitonerror 1
connect
r
sleep 100
loadfile $BOOTLOADER
sleep 100
loadfile $MAIN,0x8000
r
q
EOF
